#!/usr/bin/env bash
set -e

DEVICE_TREE="device/samsung/${DEVICE_CODENAME}"

# This hook is specific to machad3x device trees that lack lineage configs
# Skip if using dmxq-dev or other sources that already have proper configs
if [ -d "${DEVICE_TREE}/.git" ]; then
    REMOTE_URL=$(git -C "${DEVICE_TREE}" remote get-url origin 2>/dev/null || echo "")
    if [[ ! "${REMOTE_URL}" =~ Machad3x ]]; then
        echo ">> Skipping machad3x shim (using ${REMOTE_URL})"
        exit 0
    fi
fi

# --- quick shim so crDroid sees a lineage_dm1q product -----------------
LINEAGE_MK="${DEVICE_TREE}/lineage_${DEVICE_CODENAME}.mk"

# Pick the first existing product .mk to inherit (derp_, aosp_, etc.)
BASE_MK=$(ls "${DEVICE_TREE}"/*_"${DEVICE_CODENAME}".mk | grep -v "lineage_" | head -n1)

if [ -n "${BASE_MK}" ] && [ ! -f "${LINEAGE_MK}" ]; then
    echo ">> Injecting ${LINEAGE_MK} (inherits from $(basename "${BASE_MK}"))"
    cat > "${LINEAGE_MK}" <<EOF
# Auto-generated so crDroid lunch can find lineage_${DEVICE_CODENAME}
\$(call inherit-product, ${BASE_MK})
PRODUCT_NAME   := lineage_${DEVICE_CODENAME}
PRODUCT_DEVICE := ${DEVICE_CODENAME}
# Keep whatever else the original file already defines via inherit-product
EOF
fi

# Ensure AndroidProducts.mk lists the new product
APMK="${DEVICE_TREE}/AndroidProducts.mk"
grep -q "lineage_${DEVICE_CODENAME}.mk" "${APMK}" 2>/dev/null || \
    printf 'PRODUCT_MAKEFILES += $(LOCAL_DIR)/lineage_%s.mk\n' "${DEVICE_CODENAME}" >> "${APMK}"

# Provide vendor/aosp/config/common_full_phone.mk by forwarding to
# the Lineage template that ships with crDroid sources
if [ ! -f vendor/aosp/config/common_full_phone.mk ]; then
    echo ">> Injecting vendor/aosp/config/common_full_phone.mk shim"
    mkdir -p vendor/aosp/config
    cat >  vendor/aosp/config/common_full_phone.mk <<'EOF'
# Auto-generated shim: crDroid tree has no vendor/aosp base
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)
EOF
fi

# Dolby stub: build without real Dolby blobs
STUB_DOLBY_MK="hardware/dolby/dolby.mk"

# Drop a tiny placeholder so $(call inherit-product, hardware/dolby/dolby.mk) succeeds
mkdir -p "$(dirname "${STUB_DOLBY_MK}")"
if [ ! -f "${STUB_DOLBY_MK}" ]; then
    echo ">> Injecting empty ${STUB_DOLBY_MK} (skipping Dolby blobs)"
    cat > "${STUB_DOLBY_MK}" <<'EOF'
# Stub generated by entrypoint.sh - this ROM tree does not ship Dolby blobs.
EOF
fi
# -----------------------------------------------------------------------
